/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nitesh.sharma
 */
public class Calculator extends javax.swing.JFrame {
    
              double num1 = 0, num2 = 0;
              String operator = "";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        button17 = new java.awt.Button();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        t1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        buttondiv = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        buttonX = new java.awt.Button();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        buttonsub = new java.awt.Button();
        button0 = new java.awt.Button();
        buttonclear = new java.awt.Button();
        buttonvalues = new java.awt.Button();
        buttonadd = new java.awt.Button();

        textField1.setText("textField1");

        button17.setLabel("button17");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t1.setBackground(new java.awt.Color(153, 255, 255));
        t1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 153, 153));
        t1.setName(""); // NOI18N
        t1.addActionListener(this::t1ActionPerformed);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(204, 102, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(204, 204, 204));
        label1.setText("my calculator");

        button7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button7.setForeground(new java.awt.Color(204, 153, 0));
        button7.setLabel("7");
        button7.addActionListener(this::button7ActionPerformed);

        button8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button8.setForeground(new java.awt.Color(204, 153, 0));
        button8.setLabel("8");
        button8.addActionListener(this::button8ActionPerformed);

        button9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button9.setForeground(new java.awt.Color(204, 153, 0));
        button9.setLabel("9");
        button9.addActionListener(this::button9ActionPerformed);

        buttondiv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttondiv.setForeground(new java.awt.Color(204, 153, 0));
        buttondiv.setLabel("/");
        buttondiv.addActionListener(this::buttondivActionPerformed);

        button4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button4.setForeground(new java.awt.Color(204, 153, 0));
        button4.setLabel("4");
        button4.addActionListener(this::button4ActionPerformed);

        button5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button5.setForeground(new java.awt.Color(204, 153, 0));
        button5.setLabel("5");
        button5.addActionListener(this::button5ActionPerformed);

        button6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button6.setForeground(new java.awt.Color(204, 153, 0));
        button6.setLabel("6");
        button6.addActionListener(this::button6ActionPerformed);

        buttonX.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonX.setForeground(new java.awt.Color(204, 153, 0));
        buttonX.setLabel("*");
        buttonX.addActionListener(this::buttonXActionPerformed);

        button1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(204, 153, 0));
        button1.setLabel("1");
        button1.addActionListener(this::button1ActionPerformed);

        button2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button2.setForeground(new java.awt.Color(204, 153, 0));
        button2.setLabel("2");
        button2.addActionListener(this::button2ActionPerformed);

        button3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button3.setForeground(new java.awt.Color(204, 153, 0));
        button3.setLabel("3");
        button3.addActionListener(this::button3ActionPerformed);

        buttonsub.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonsub.setForeground(new java.awt.Color(204, 153, 0));
        buttonsub.setLabel("-");
        buttonsub.addActionListener(this::buttonsubActionPerformed);

        button0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button0.setForeground(new java.awt.Color(204, 153, 0));
        button0.setLabel("0");
        button0.addActionListener(this::button0ActionPerformed);

        buttonclear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonclear.setForeground(new java.awt.Color(204, 153, 0));
        buttonclear.setLabel("C");
        buttonclear.addActionListener(this::buttonclearActionPerformed);

        buttonvalues.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonvalues.setForeground(new java.awt.Color(204, 153, 0));
        buttonvalues.setLabel("=");
        buttonvalues.addActionListener(this::buttonvaluesActionPerformed);

        buttonadd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonadd.setForeground(new java.awt.Color(204, 153, 0));
        buttonadd.setLabel("+");
        buttonadd.addActionListener(this::buttonaddActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonX, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonsub, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonvalues, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttondiv, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(buttondiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(button3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(button2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(buttonsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonadd, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonclear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonvalues, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
           
// TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
            t1.setText(t1.getText() + "7");        
// TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
           t1.setText(t1.getText() + "4");
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
             t1.setText(t1.getText() + "6");        
// TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       t1.setText(t1.getText() + "1");
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
       t1.setText(t1.getText() + "3");
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
       t1.setText(t1.getText() + "0");        
// TODO add your handling code here:
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonvaluesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonvaluesActionPerformed
                      
        
            
       if(t1.getText().equals("") || operator.equals("")) return;

    num2 = Double.parseDouble(t1.getText());

    double result = 0;

    if(operator.equals("+")) {
        result = num1 + num2;
    }
    else if(operator.equals("-")) {
        result = num1 - num2;
    }
    else if(operator.equals("*")) {
        result = num1 * num2;
    }
    else if(operator.equals("/")) {
        if(num2 == 0) {
            t1.setText("Error");
            return;
        }
        result = num1 / num2;
    }

    t1.setText("" + result);

    // ✅ RESET
    operator = "";
    num1 = result;  // smooth next calculation
// t1.setText(t1.getText() + "7");        
// TODO add your handling code here:
    }//GEN-LAST:event_buttonvaluesActionPerformed

    private void buttonsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsubActionPerformed

    
      //  if(t1.getText().equals("")) return;
        num1 = Double.parseDouble(t1.getText());
        operator = "-";
        t1.setText("");
   
        
// t1.setText(t1.getText() + "8");
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsubActionPerformed

    private void buttonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonclearActionPerformed

        t1.setText("");
        num1 = 0;
        num2 = 0;
        operator = "";
        
        
// t1.setText = "";      
// TODO add your handling code here:
        
    }//GEN-LAST:event_buttonclearActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
       t1.setText(t1.getText() + "8");
        // TODO add your handling code here:
    }//GEN-LAST:event_button8ActionPerformed

    private void buttondivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondivActionPerformed
       
             // if(t1.getText().equals("")) return;
        num1 = Double.parseDouble(t1.getText());
        operator = "/";
        t1.setText("");
        
// t1.setText(t1.getText() + "7");
// TODO add your handling code here:
    }//GEN-LAST:event_buttondivActionPerformed

    private void buttonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonaddActionPerformed
        
       // if(t1.getText().equals("")) return;
        num1 = Double.parseDouble(t1.getText());
        operator = "+";
        t1.setText("");
        
//t1.setText(t1.getText() + "7");
// TODO add your handling code here:
    }//GEN-LAST:event_buttonaddActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
               t1.setText(t1.getText() + "9");
        // TODO add your handling code here:
    }//GEN-LAST:event_button9ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
                         t1.setText(t1.getText() + "5");
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
                      t1.setText(t1.getText() + "2");
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void buttonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXActionPerformed
         
      //  if(t1.getText().equals("")) return;
        num1 = Double.parseDouble(t1.getText());
        operator = "*";
        t1.setText("");  
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_buttonXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button0;
    private java.awt.Button button1;
    private java.awt.Button button17;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private java.awt.Button buttonX;
    private java.awt.Button buttonadd;
    private java.awt.Button buttonclear;
    private java.awt.Button buttondiv;
    private java.awt.Button buttonsub;
    private java.awt.Button buttonvalues;
    private javax.swing.JLayeredPane jLayeredPane1;
    private java.awt.Label label1;
    private java.awt.TextField t1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
