

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nitesh.sharma
 */
public class DigitalClock extends javax.swing.JFrame {
      
    
    private Timer timer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DigitalClock.class.getName());

    /**
     * Creates new form DigitalClock
     */
    public DigitalClock() {
        initComponents();
       timer = new Timer(10, e -> updateTime());
        timer.start();
    }

    // ✅ TIME + DATE UPDATE
    private void updateTime() {

        Date now = new Date();

        // Time with milliseconds
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss a");
        timelabel.setText(timeFormat.format(now));

        // Date
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEE, dd-MM-yyyy");
        datelabel.setText(dateFormat.format(now));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        Startbutton = new javax.swing.JButton();
        Stopbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Digital Clock");

        datelabel.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        datelabel.setForeground(new java.awt.Color(255, 204, 153));
        datelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datelabel.setLabelFor(datelabel);
        datelabel.setText("Date");
        datelabel.setToolTipText("");

        timelabel.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        timelabel.setForeground(new java.awt.Color(255, 255, 255));
        timelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timelabel.setText("00 : 00 : 00");

        Startbutton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Startbutton.setForeground(new java.awt.Color(204, 204, 0));
        Startbutton.setText("Start");
        Startbutton.addActionListener(this::StartbuttonActionPerformed);

        Stopbutton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Stopbutton.setForeground(new java.awt.Color(255, 102, 0));
        Stopbutton.setText("Stop");
        Stopbutton.addActionListener(this::StopbuttonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 129, Short.MAX_VALUE)
                .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Startbutton)
                        .addGap(29, 29, 29)
                        .addComponent(Stopbutton)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datelabel)
                .addGap(24, 24, 24)
                .addComponent(timelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Startbutton)
                    .addComponent(Stopbutton))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartbuttonActionPerformed
        timer.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_StartbuttonActionPerformed

    private void StopbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopbuttonActionPerformed
              timer.stop();
        // TODO add your handling code here:
    }//GEN-LAST:event_StopbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DigitalClock().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Startbutton;
    private javax.swing.JButton Stopbutton;
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel timelabel;
    // End of variables declaration//GEN-END:variables
}
