/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;

/**
 *
 * @author TusharSharma
 */
public class GuessingNumberGame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuessingNumberGame.class.getName());
          int numberToGuess;
          int attempts = 0;
    /**
     * Creates new form GuessingNumbergame
     */
    public GuessingNumberGame() {
     
       
        initComponents();
        startGame();

// Enter key = Guess
inputField.addActionListener(e -> guessbtn.doClick());
    }
  private void startGame(){
    numberToGuess = new Random().nextInt(100) + 1;
    attempts = 0;

    attemptLabel.setText("Attempts : 0");
    hintLabel.setText("New Game Started!");
    inputField.setText("");
    inputField.setEditable(true); // CRITICAL: Re-enable input on reset
        inputField.requestFocus();    // Focus for better UX
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlelebal = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();
        guessbtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();
        attemptLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        titlelebal.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        titlelebal.setForeground(new java.awt.Color(51, 0, 51));
        titlelebal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelebal.setText("GUESS NO (1-100)");

        inputField.setBackground(new java.awt.Color(204, 204, 255));
        inputField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputField.addActionListener(this::inputFieldActionPerformed);

        guessbtn.setBackground(new java.awt.Color(102, 204, 0));
        guessbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        guessbtn.setText("Guess");
        guessbtn.addActionListener(this::guessbtnActionPerformed);

        resetbtn.setBackground(new java.awt.Color(102, 204, 0));
        resetbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.addActionListener(this::resetbtnActionPerformed);

        hintLabel.setBackground(new java.awt.Color(255, 204, 102));
        hintLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hintLabel.setForeground(new java.awt.Color(0, 0, 255));
        hintLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintLabel.setText("Enter Your Guess.....");

        attemptLabel.setBackground(new java.awt.Color(255, 102, 102));
        attemptLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        attemptLabel.setForeground(new java.awt.Color(204, 204, 0));
        attemptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attemptLabel.setText("Attempts : 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(titlelebal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(guessbtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(resetbtn))
                                .addComponent(attemptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titlelebal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessbtn)
                    .addComponent(resetbtn))
                .addGap(28, 28, 28)
                .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(attemptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Meiryo", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NoGuessingGame");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(153, 153, 0), new java.awt.Color(153, 102, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed

    private void guessbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessbtnActionPerformed
             
       String input = inputField.getText().trim();

        if (input.isEmpty()) {
            hintLabel.setText("Enter a number ⚠");
            return;
        }

        try {
            int guess = Integer.parseInt(input);

            if (guess < 1 || guess > 100) {
                hintLabel.setText("Range: 1-100 ⚠");
                return;
            }

            attempts++;
            attemptLabel.setText("Attempts : " + attempts);

            if (guess < numberToGuess) {
                hintLabel.setText("Too Low 📉");
                inputField.setText(""); // Clear for next guess
            } else if (guess > numberToGuess) {
                hintLabel.setText("Too High 📈");
                inputField.setText(""); // Clear for next guess
            } else {
                hintLabel.setText("Correct! 🎉 Answer: " + numberToGuess);
                inputField.setEditable(false); // Disable until Reset
            }
        } catch (NumberFormatException e) {
            hintLabel.setText("Invalid number ❌");
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_guessbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
                                        
                     startGame();
                    // inputField.setEditable(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_resetbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new GuessingNumberGame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attemptLabel;
    private javax.swing.JButton guessbtn;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resetbtn;
    private javax.swing.JLabel titlelebal;
    // End of variables declaration//GEN-END:variables
}
